#!/bin/sh

source /etc/upstart/functions

LOG_MODULE=`basename "$0"`
if [ $1 -eq 1 ]; then
    echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
    f_log I "$LOG_MODULE" "changePerfMode" "Switched to performance mode";
elif [ $1 -eq 0 ]; then
    echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
    f_log I "$LOG_MODULE" "changePerfMode" "Switched to ondemand mode";
fi

